name: Node.js Package Release

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  release:
    uses: venkydam/mytestworkflow/.github/workflows/node-release.yml@main
    permissions:
      id-token: write
      contents: write
    with:
      node-version: "20"
      working-directory: "."
